// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: likes.sql

package db

import (
	"context"
)

const getLikes = `-- name: GetLikes :many
SELECT id, liked_user, target_post FROM post_like
`

func (q *Queries) GetLikes(ctx context.Context) ([]PostLike, error) {
	rows, err := q.db.QueryContext(ctx, getLikes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostLike
	for rows.Next() {
		var i PostLike
		if err := rows.Scan(&i.ID, &i.LikedUser, &i.TargetPost); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
