// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Comment struct {
	ID         uuid.UUID
	Texts      string
	PostedBy   uuid.UUID
	TargetPost uuid.UUID
}

type CommentLike struct {
	ID            int64
	LikedUser     uuid.UUID
	TargetComment uuid.UUID
}

type Follow struct {
	ID       int64
	FromUser uuid.UUID
	ToUser   uuid.UUID
}

type Post struct {
	ID        uuid.UUID
	Title     string
	Body      string
	PostedBy  uuid.UUID
	Photo     string
	CreatedAt time.Time
	UpdatedAt sql.NullTime
}

type PostLike struct {
	ID         int64
	LikedUser  uuid.UUID
	TargetPost uuid.UUID
}

type User struct {
	ID       uuid.UUID
	Email    string
	Name     string
	Password string
	Pic      string
}
