// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
)

type Author struct {
	ID   int64
	Name string
	Bio  sql.NullString
}

type User struct {
	ID       int32
	Email    sql.NullString
	Name     sql.NullString
	Password sql.NullString
}
